### ISSUE TITLE
🐛 회원 가입할때, 네비게이션 바가 없어서 뒤로 가기 불가능

### ISSUE THREAD

**Issue by obtusa07** [DeveloperAcademy-POSTECH/MacC-Dime-Flicker#174]
### 🙅 Current State

한번 가입하기를 누르면 끝까지 가는 방법밖에 없습니다..

### 💁 예상 작업 기간

???

**Comment by Kim-Yeon-ho** [comment]
굳이 필요하다고 생각이 들지 않아서 없엤습니다. 제가 말한 걸로 기억하고있는데 안해드렸나요...?
@obtusa07

**Comment by obtusa07** [comment]
이거 들은거 같기도 한데 메인랩에서 4~5명한테 만져보라고 하니까 다 이게 없다고 지적하더라고요 있는게 좋지 않을까요?
