### ISSUE TITLE
📝 깃이모지 관련 제안사항

### ISSUE THREAD

**Issue by Rookie0031** [DeveloperAcademy-POSTECH/MacC-Dime-Flicker#29]
## 배경
초기 코드컨벤션에서 깃이모지를 적극적으로 활용해보기로 하였습니다. 이유는 어떤 목적으로 작성된 문서인지 알기 쉽게하자는 것이었고 현재 이슈와 PR, 브랜치명의 맨앞에 사용되고 있습니다.

## 문제
깃이모지가 워낙 많아 상황에 어떤 이모지를 사용해야하는지 따로 찾아봐야하는 귀찮음이 있고, 그 중에는 사용되지 않고있는 이모지가 훨씬 많습니다.
[깃이모지 모음](https://inpa.tistory.com/entry/GIT-⚡%EF%B8%8F-Gitmoji-사용법-Gitmoji-cli)

## 제안
그래서 자주 쓰는 이모지를 리드미, 이슈 템플릿, PR 템플릿에 모두 추가하는 걸 제안합니다.

🎨 코드 구조/형태 개선 (리소스 이동, 파일 추가 및 삭제 포함)
⚡ 성능개선 (정량적으로 측정가능한 성능개선만 사용)
🐛 버그수정
🚑 긴급 수정
✨ 새 기능
📝 문서 추가/ 작성
💄 UI 관련 코드 수정

**Comment by PecanPiePOS** [comment]
모든 곳에 쓰는 것에 대해 동의합니닷
