### ISSUE TITLE
[Feature]: ProfileView의 Profile Card에 네비게이션 기능을 부여해야 합니다.

### ISSUE THREAD

**Issue by obtusa07** [DeveloperAcademy-POSTECH/MacC-Dime-Flicker#53]
### 💡 Feature 설명

ProfileViewController에는 TableView Cell의 Header로 유저의 사용자 정보를 담은 카드가 존재합니다. 해당 영역을 탭할 시 회원가입 화면으로 이동하는 기능입니다.

### 🙏 Prepare Issue(Optional)

#15

### 🤝 Related View(Optional)

- ProfileView

### ⭐️ 우선순위

★★★★

### 💁 예상 작업 기간

22.11.16 ~ 22.11.16

**Comment by Kim-Yeon-ho** [comment]
@obtusa07  이거 이슈 닫겠슴다!
